-- Generated by Veritas from Vector AND
library ieee;
use ieee.std_logic_1164.all;

entity Vector_AND is
  port (
    A : in std_logic_vector(3 downto 0);
    B : in std_logic_vector(3 downto 0);
    Y : out std_logic_vector(3 downto 0)
  );
end entity Vector_AND;

architecture rtl of Vector_AND is
  signal A_B : std_logic_vector(3 downto 0);
begin
  A_B <= A and B;
  Y <= A_B;
end architecture rtl;
