export const MAX_CIRCUIT_NODES = 256
export const MAX_CIRCUIT_CONNECTIONS = 512
export const MAX_CIRCUIT_NAME_LENGTH = 200
export const MAX_CIRCUIT_LABEL_LENGTH = 120
export const MAX_WIRELESS_CHANNEL_LENGTH = 64
export const MAX_CIRCUIT_SERIALIZED_BYTES = 500_000
