import { CircuitValidationError, editorInputCount, validateCircuit, type CircuitDocument, type CircuitNode } from './editorModel'
import { normalizeCircuitDocument } from './documentContract'
import { resolveWirelessChannels } from './wirelessChannels'

export type CircuitExportFormat = 'verilog' | 'vhdl'

export function exportCircuit(document: CircuitDocument, format: CircuitExportFormat): string {
  return format === 'verilog' ? exportVerilog(document) : exportVhdl(document)
}

export function exportVerilog(document: CircuitDocument): string {
  const normalized = normalizeCircuitDocument(document)
  assertValid(normalized)
  const model = buildExportModel(normalized)
  const moduleName = sanitizeIdentifier(normalized.name, 'veritas_circuit')
  const ports = [
    ...model.inputs.map((node) => `${verilogDirection(node, 'input', model)}`),
    ...model.outputs.map((node) => `${verilogDirection(node, 'output', model)}`),
  ]
  const declarations = model.internalNodes.map((node) => `  wire${verilogWidth(node)} ${model.names.get(node.id)};`)
  const assignments = model.nodes.flatMap((node) => {
    if (node.type === 'input' || node.type === 'output') return []
    return [`  assign ${model.names.get(node.id)} = ${verilogExpression(node, model)};`]
  })
  const outputAssignments = model.outputs.map((node) => `  assign ${model.names.get(node.id)} = ${sourceExpression(node, model)};`)

  return [
    `// Generated by Veritas from ${normalized.name}`,
    `module ${moduleName} (`,
    ports.map((port, index) => `  ${port}${index === ports.length - 1 ? '' : ','}`).join('\n'),
    ');',
    ...(declarations.length > 0 ? ['', ...declarations] : []),
    '',
    ...assignments,
    ...outputAssignments,
    'endmodule',
    '',
  ].join('\n')
}

export function exportVhdl(document: CircuitDocument): string {
  const normalized = normalizeCircuitDocument(document)
  assertValid(normalized)
  const model = buildExportModel(normalized)
  const entityName = sanitizeIdentifier(normalized.name, 'veritas_circuit')
  const ports = [
    ...model.inputs.map((node) => `    ${model.names.get(node.id)} : in ${vhdlType(node)}`),
    ...model.outputs.map((node) => `    ${model.names.get(node.id)} : out ${vhdlType(node)}`),
  ]
  const declarations = model.internalNodes.map((node) => `  signal ${model.names.get(node.id)} : ${vhdlType(node)};`)
  const assignments = model.nodes.flatMap((node) => {
    if (node.type === 'input' || node.type === 'output') return []
    return [`  ${model.names.get(node.id)} <= ${vhdlExpression(node, model)};`]
  })
  const outputAssignments = model.outputs.map((node) => `  ${model.names.get(node.id)} <= ${sourceExpression(node, model)};`)

  return [
    '-- Generated by Veritas from ' + normalized.name,
    'library ieee;',
    'use ieee.std_logic_1164.all;',
    '',
    `entity ${entityName} is`,
    '  port (',
    ports.map((port, index) => `${port}${index === ports.length - 1 ? '' : ';'}`).join('\n'),
    '  );',
    `end entity ${entityName};`,
    '',
    `architecture rtl of ${entityName} is`,
    ...declarations,
    'begin',
    ...assignments,
    ...outputAssignments,
    `end architecture rtl;`,
    '',
  ].join('\n')
}

function assertValid(document: CircuitDocument): void {
  const issues = validateCircuit(document, { allowBuses: true })
  if (issues.length > 0) throw new CircuitValidationError(issues)
}

interface ExportModel {
  nodes: CircuitNode[]
  inputs: CircuitNode[]
  outputs: CircuitNode[]
  internalNodes: CircuitNode[]
  names: Map<string, string>
  inputsByNode: Map<string, Map<number, { node: string; port?: number }>>
}

function buildExportModel(document: CircuitDocument): ExportModel {
  const nodes = [...document.nodes].sort((a, b) => a.id.localeCompare(b.id))
  const allocator = new NameAllocator()
  const names = new Map<string, string>()
  for (const node of nodes) names.set(node.id, allocator.allocate(node.label ?? node.id, node.id))
  const inputs = nodes.filter((node) => node.type === 'input')
  const outputs = nodes.filter((node) => node.type === 'output')
  const internalNodes = nodes.filter((node) => node.type !== 'input' && node.type !== 'output')
  const inputsByNode = new Map<string, Map<number, { node: string; port?: number }>>()
  for (const connection of document.connections) {
    const target = inputsByNode.get(connection.target.node) ?? new Map()
    target.set(connection.target.port, connection.source)
    inputsByNode.set(connection.target.node, target)
  }
  const wirelessResolution = resolveWirelessChannels(
    document.nodes
      .filter((node) => node.type === 'transmitter' || node.type === 'receiver')
      .map((node) => ({
        nodeId: node.id,
        channel: node.options?.channel ?? '',
        kind: node.type as 'transmitter' | 'receiver',
        width: nodeWidth(node),
      })),
  )
  if (wirelessResolution.issues.length > 0) throw new CircuitValidationError(wirelessResolution.issues.map((issue) => ({ code: 'invalid-node', nodeId: issue.nodeId, message: issue.message })))
  for (const channel of wirelessResolution.channels) {
    for (const receiver of channel.receivers) {
      const target = inputsByNode.get(receiver.nodeId) ?? new Map()
      target.set(0, { node: channel.transmitter.nodeId })
      inputsByNode.set(receiver.nodeId, target)
    }
  }
  return { nodes, inputs, outputs, internalNodes, names, inputsByNode }
}

function sourceExpression(node: CircuitNode, model: ExportModel): string {
  const source = model.inputsByNode.get(node.id)?.get(0)
  if (!source) throw new Error(`Saída ${node.id} sem origem.`)
  return model.names.get(source.node) ?? sanitizeIdentifier(source.node, 'signal')
}

function verilogExpression(node: CircuitNode, model: ExportModel): string {
  if (node.type === 'constant') return verilogLiteral(nodeWidth(node), node.options?.value ?? false)
  if (node.type === 'transmitter' || node.type === 'receiver') return operandsFor(node, model).map((source) => model.names.get(source.node) ?? sanitizeIdentifier(source.node, 'signal'))[0] ?? verilogLiteral(nodeWidth(node), false)
  const operands = operandsFor(node, model).map((source) => model.names.get(source.node) ?? sanitizeIdentifier(source.node, 'signal'))
  if (node.type === 'not') return `~${operands[0]}`
  const operator = node.type === 'and' ? ' & ' : node.type === 'or' ? ' | ' : ' ^ '
  return operands.join(operator)
}

function vhdlExpression(node: CircuitNode, model: ExportModel): string {
  if (node.type === 'constant') return vhdlLiteral(nodeWidth(node), node.options?.value ?? false)
  if (node.type === 'transmitter' || node.type === 'receiver') return operandsFor(node, model).map((source) => model.names.get(source.node) ?? sanitizeIdentifier(source.node, 'signal'))[0] ?? vhdlLiteral(nodeWidth(node), false)
  const operands = operandsFor(node, model).map((source) => model.names.get(source.node) ?? sanitizeIdentifier(source.node, 'signal'))
  if (node.type === 'not') return `not ${operands[0]}`
  const operator = node.type === 'and' ? ' and ' : node.type === 'or' ? ' or ' : ' xor '
  return operands.join(operator)
}

function verilogDirection(node: CircuitNode, direction: 'input' | 'output', model: ExportModel): string {
  return `${direction}${verilogWidth(node)} ${model.names.get(node.id)}`
}

function verilogWidth(node: CircuitNode): string {
  const width = nodeWidth(node)
  return width === 1 ? '' : ` [${width - 1}:0]`
}

function vhdlType(node: CircuitNode): string {
  const width = nodeWidth(node)
  return width === 1 ? 'std_logic' : `std_logic_vector(${width - 1} downto 0)`
}

function verilogLiteral(width: number, value: boolean): string {
  return width === 1 ? (value ? "1'b1" : "1'b0") : `{${width}{1'b${value ? '1' : '0'}}}`
}

function vhdlLiteral(width: number, value: boolean): string {
  return width === 1 ? (value ? "'1'" : "'0'") : `(others => '${value ? '1' : '0'}')`
}

function nodeWidth(node: CircuitNode): number {
  return node.options?.width ?? 1
}

function operandsFor(node: CircuitNode, model: ExportModel) {
  const inputMap = model.inputsByNode.get(node.id)
  const count = node.type === 'receiver' ? 1 : editorInputCount(node.type)
  return Array.from({ length: count }, (_, port) => inputMap?.get(port)).filter((source): source is { node: string; port?: number } => Boolean(source))
}

class NameAllocator {
  private readonly used = new Set<string>()

  allocate(preferred: string, fallback: string): string {
    const base = sanitizeIdentifier(preferred || fallback, 'signal')
    let candidate = base
    let index = 2
    while (this.used.has(candidate.toLowerCase())) candidate = `${base}_${index++}`
    this.used.add(candidate.toLowerCase())
    return candidate
  }
}

function sanitizeIdentifier(value: string, fallback: string): string {
  const cleaned = value.normalize('NFKD').replace(/[\u0300-\u036f]/g, '').replace(/[^A-Za-z0-9_$]/g, '_').replace(/_+/g, '_')
  const candidate = cleaned.replace(/^_+|_+$/g, '') || fallback
  const prefixed = /^[0-9]/.test(candidate) ? `n_${candidate}` : candidate
  const reserved = new Set(['module', 'input', 'output', 'wire', 'assign', 'begin', 'end', 'entity', 'architecture', 'signal', 'port', 'in', 'out', 'and', 'or', 'not', 'xor'])
  return reserved.has(prefixed.toLowerCase()) ? `v_${prefixed}` : prefixed
}
