import { describe, expect, it } from 'vitest'
import { createCircuitDocument, exportVerilog, exportVhdl, type CircuitDocument } from '../../src/circuit'
import {
  HDL_ACCEPTANCE_IDS,
  HDL_TOOLCHAINS,
  isAcceptedHdlStatus,
  renderHdlReport,
  sanitizeHdlMessage,
} from '../../scripts/hdlAcceptanceContract.mjs'

const vectorAnd: CircuitDocument = {
  ...createCircuitDocument('Vector AND'),
  nodes: [
    { id: 'input-a', type: 'input', position: { x: 0, y: 0 }, label: 'A', options: { width: 4 } },
    { id: 'input-b', type: 'input', position: { x: 0, y: 100 }, label: 'B', options: { width: 4 } },
    { id: 'gate', type: 'and', position: { x: 200, y: 50 }, label: 'A&B', options: { width: 4 } },
    { id: 'output', type: 'output', position: { x: 400, y: 50 }, label: 'Y', options: { width: 4 } },
  ],
  connections: [
    { source: { node: 'input-a' }, target: { node: 'gate', port: 0 } },
    { source: { node: 'input-b' }, target: { node: 'gate', port: 1 } },
    { source: { node: 'gate' }, target: { node: 'output', port: 0 } },
  ],
}

const expectedVerilog = `// Generated by Veritas from Vector AND
module Vector_AND (
  input [3:0] A,
  input [3:0] B,
  output [3:0] Y
);

  wire [3:0] A_B;

  assign A_B = A & B;
  assign Y = A_B;
endmodule`

const expectedVhdl = `-- Generated by Veritas from Vector AND
library ieee;
use ieee.std_logic_1164.all;

entity Vector_AND is
  port (
    A : in std_logic_vector(3 downto 0);
    B : in std_logic_vector(3 downto 0);
    Y : out std_logic_vector(3 downto 0)
  );
end entity Vector_AND;

architecture rtl of Vector_AND is
  signal A_B : std_logic_vector(3 downto 0);
begin
  A_B <= A and B;
  Y <= A_B;
end architecture rtl;`

describe('contrato de aceitação HDL', () => {
  it('mantém IDs e toolchains explícitos', () => {
    expect(HDL_ACCEPTANCE_IDS).toEqual(['HDL-001', 'HDL-002', 'HDL-003'])
    expect(HDL_TOOLCHAINS).toEqual(['iverilog', 'ghdl'])
    expect(isAcceptedHdlStatus('PASS')).toBe(true)
    expect(isAcceptedHdlStatus('SKIP')).toBe(true)
    expect(isAcceptedHdlStatus('FAIL')).toBe(true)
    expect(isAcceptedHdlStatus('PENDING')).toBe(false)
  })

  it('gera exatamente as fixtures equivalentes Verilog e VHDL', () => {
    expect(exportVerilog(vectorAnd).trim()).toBe(expectedVerilog)
    expect(exportVhdl(vectorAnd).trim()).toBe(expectedVhdl)
  })

  it('sanitiza mensagens e renderiza relatório contratual', () => {
    const message = sanitizeHdlMessage('Bearer secret token=abc password=hunter2')
    expect(message).not.toContain('secret')
    expect(message).not.toContain('abc')
    expect(message).not.toContain('hunter2')
    expect(renderHdlReport([
      { id: 'HDL-001', status: 'PASS', operation: 'compilação Verilog', message: 'ok' },
      { id: 'HDL-002', status: 'SKIP', operation: 'compilação VHDL', message },
      { id: 'HDL-003', status: 'PASS', operation: 'exportador', message: 'ok' },
    ], '2026-08-21T00:00:00.000Z')).toContain('Resumo: 2 PASS, 0 FAIL, 1 SKIP.')
  })
})
